# Generated by Django 5.1.1 on 2024-09-16 09:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_customer_city_customer_country_customer_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 16, 9, 55, 17, 641962, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='customer',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 16, 9, 55, 17, 641962, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 16, 9, 55, 17, 641962, tzinfo=datetime.timezone.utc)),
        ),
    ]
